FROM node:22-alpine AS builder
WORKDIR /app
COPY client/package*.json ./
RUN npm install
COPY client/ ./
RUN npm run build

FROM nginx:alpine AS runner
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf.template
EXPOSE 80
CMD ["/bin/sh", "-c", "export BACKEND_URL=$(echo -n \"$BACKEND_URL\" | tr -d '\\n\\r') && export RESOLVER=$(awk 'NR==1 && /^nameserver/{print $2}' /etc/resolv.conf) && envsubst '${BACKEND_URL} ${RESOLVER}' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
